### ISSUE TITLE
the problem about 'closed_loop_nonreactive_agents', 'closed_loop_reactive_agents'

### ISSUE THREAD

**Issue by 942411526** [MCZhi/GameFormer-Planner#23]
Dear authors,
thanks for your great work. There are a problem when we test the closed loop.

Iteration 148: 0.668 s
Running ego_jerk with error: window_length must be odd.
Running simulation:   0%|                                                                                                                                       | 0/140 [01:20<?, ?it/s]
Traceback (most recent call last):
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 112, in compute_metric_results
    metric_results[metric.name] = metric.compute(history, scenario=scenario)
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/common/ego_jerk.py", line 30, in compute
    metric_statistics: List[MetricStatistics] = self._compute_statistics(
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/metrics/evaluation_metrics/base/within_bound_metric_base.py", line 97, in _compute_statistics
    ego_pose_values = extract_function(ego_pose_states, **extract_function_params)
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/metrics/utils/state_extractors.py", line 237, in extract_ego_jerk
    ego_acceleration = extract_ego_acceleration(ego_states=ego_states, acceleration_coordinate=acceleration_coordinate)
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/metrics/utils/state_extractors.py", line 214, in extract_ego_acceleration
    acceleration = savgol_filter(
  File "/home/yx/anaconda3/envs/nuplan/lib/python3.9/site-packages/scipy/signal/_savitzky_golay.py", line 335, in savgol_filter
    coeffs = savgol_coeffs(window_length, polyorder, deriv=deriv, delta=delta)
  File "/home/yx/anaconda3/envs/nuplan/lib/python3.9/site-packages/scipy/signal/_savitzky_golay.py", line 102, in savgol_coeffs
    raise ValueError("window_length must be odd.")
ValueError: window_length must be odd.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yx/github_pr/Gamebaseline/run_nuplan_test.py", line 224, in <module>
    main(args)
  File "/home/yx/github_pr/Gamebaseline/run_nuplan_test.py", line 204, in main
    build_simulation(experiment_name, planner, scenarios, output_dir, simulation_dir, metric_dir)
  File "/home/yx/github_pr/Gamebaseline/run_nuplan_test.py", line 118, in build_simulation
    report = simulation_runner.run()
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 128, in run
    self.simulation.callback.on_simulation_end(self.simulation.setup, self.planner, self.simulation.history)
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/simulation/callback/multi_callback.py", line 68, in on_simulation_end
    callback.on_simulation_end(setup, planner, history)
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 102, in on_simulation_end
    run_metric_engine(
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/simulation/callback/metric_callback.py", line 24, in run_metric_engine
    metric_files = metric_engine.compute(history, scenario=scenario, planner_name=planner_name)
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 133, in compute
    all_metrics_results = self.compute_metric_results(history=history, scenario=scenario)
  File "/home/yx/github_pr/DTPP/nuplan-devkit/nuplan/planning/metrics/metric_engine.py", line 119, in compute_metric_results
    raise RuntimeError(f"Metric Engine failed with: {e}")
RuntimeError: Metric Engine failed with: window_length must be odd.

I don't know how to deal this problem

**Comment by 942411526** [comment]
open loop is fine
